[tool.poetry]
name = "django-tailwind"
version = "3.8.0"
description = "Tailwind CSS Framework for Django projects"
authors = ["Tim Kamanin <tim@timonweb.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/timonweb/django-tailwind"
keywords = ["django", "tailwind", "css"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Environment :: Web Environment",
    "Framework :: Django"
]
packages = [
    { include = "tailwind", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10.0"
django = ">=3.2.14"
django-browser-reload = {version = "^1.12.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"
pytest-django = "^4.7.0"
tox = "^4.11.4"
pre-commit = "^3.6.0"
isort = "^5.13.2"
flake8 = "^6.1.0"
black = "^23.12.0"
Sphinx = "^4.3.1"
recommonmark = "^0.7.1"
sphinx-rtd-theme = "^1.2.0"

[tool.poetry.extras]
reload = ["django-browser-reload"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
